
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x700")
window.configure(bg = "#202225")


canvas = Canvas(
    window,
    bg = "#202225",
    height = 700,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    604.4124145507812,
    62.13761901855469,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_2 = Button(
    image=image_image_2,
    bd=0,
    highlightthickness=0,
    bg="#202225", 
    #command=your_command_function  # Replace "your_command_function" with the actual command function
)

image_2.place(
    x=1020.0,
    y=623.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    533.0,
    620.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#2F3235",
    fg="#FFFFFF",  # Set text color to white
    highlightthickness=0,
    font=("Magra", 24)  # Increase font size to 24
)
entry_1.place(
    x=209.0,
    y=567.0,
    width=648.0,
    height=104.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = Button(
    image=image_image_3,
    bd=0,
    highlightthickness=0,
    bg="#202225", 
    #command=your_command_function  # Replace "your_command_function" with the actual command function
)

image_3.place(
    x=1075.0,
    y=570.0
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_4 = canvas.create_image(
    60.0,
    350.0,
    image=image_image_4
)


image_image_2 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_2 = Button(
    image=image_image_2,
    bd=0,
    highlightthickness=0,
    bg="#202225", 
    #command=your_command_function  # Replace "your_command_function" with the actual command function
)

image_2.place(
    x=1015.0,
    y=595.0
)


image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = Button(
    image=image_image_5,
    bd=0,
    highlightthickness=0,
    bg="#202225", 
    #command=your_command_function  # Replace "your_command_function" with the actual command function
)

image_5.place(
    x=930.0,
    y=590.0
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    60.0,
    49.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    59.0,
    152.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    59.0,
    647.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    660.0,
    295.0,
    image=image_image_9
)
window.resizable(False, False)
window.mainloop()
